version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - odiroot
  labels:
  - dependencies
  ignore:
  - dependency-name: boto3
    versions:
    - "> 1.11.0, < 1.12"
  - dependency-name: boto3
    versions:
    - "> 1.12.0, < 1.13"
  - dependency-name: boto3
    versions:
    - "> 1.13.1, < 1.14"
  - dependency-name: boto3
    versions:
    - "> 1.14.0, < 1.15"
  - dependency-name: boto3
    versions:
    - "> 1.15.4, < 1.16"
  - dependency-name: boto3
    versions:
    - "> 1.16.17, < 1.17"
  - dependency-name: django
    versions:
    - "> 3.0.6, < 3.1"
  - dependency-name: ipython
    versions:
    - ">= 7.12.a, < 7.13"
  - dependency-name: ipython
    versions:
    - ">= 7.15.a, < 7.16"
  - dependency-name: markdown
    versions:
    - "> 3.3.3, < 3.4"
  - dependency-name: pillow
    versions:
    - "> 8.1.0, < 8.2"
  - dependency-name: sentry-sdk
    versions:
    - "> 0.14.1, < 0.15"
  - dependency-name: sentry-sdk
    versions:
    - "> 0.17.0, < 0.18"
  - dependency-name: boto3
    versions:
    - 1.17.0
    - 1.17.1
    - 1.17.10
    - 1.17.11
    - 1.17.12
    - 1.17.14
    - 1.17.15
    - 1.17.16
    - 1.17.17
    - 1.17.18
    - 1.17.19
    - 1.17.2
    - 1.17.20
    - 1.17.21
    - 1.17.22
    - 1.17.23
    - 1.17.24
    - 1.17.25
    - 1.17.26
    - 1.17.27
    - 1.17.28
    - 1.17.29
    - 1.17.3
    - 1.17.30
    - 1.17.33
    - 1.17.34
    - 1.17.35
    - 1.17.36
    - 1.17.37
    - 1.17.39
    - 1.17.4
    - 1.17.40
    - 1.17.41
    - 1.17.43
    - 1.17.44
    - 1.17.45
    - 1.17.46
    - 1.17.47
    - 1.17.48
    - 1.17.49
    - 1.17.5
    - 1.17.50
    - 1.17.51
    - 1.17.52
    - 1.17.53
    - 1.17.54
    - 1.17.55
    - 1.17.56
    - 1.17.57
    - 1.17.58
    - 1.17.6
    - 1.17.7
    - 1.17.8
    - 1.17.9
  - dependency-name: djangorestframework
    versions:
    - 3.12.3
  - dependency-name: ipython
    versions:
    - 7.20.0
    - 7.21.0
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
    - 0.20.3
