# Generated by Django 2.2.3 on 2019-08-11 20:18

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import hashid_field.field
import postcards.models
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=32)),
            ],
            bases=(common.models.UUIDMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                        editable=False,
                        min_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Readable postcard ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'face',
                    models.ImageField(
                        blank=True,
                        upload_to=postcards.models.face_upload_path,
                        verbose_name='Postcard face design',
                    ),
                ),
                (
                    'from_country',
                    django_countries.fields.CountryField(max_length=2),
                ),
                ('from_city', models.CharField(max_length=32)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(null=True)),
                (
                    'to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='cards',
                        to='postcards.Contact',
                        verbose_name='Receiver',
                    ),
                ),
            ],
        ),
    ]
