# Generated by Django 2.2.3 on 2019-08-10 21:27

from django.db import migrations, models
import django_countries.fields
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                (
                    'id',
                    hashid_field.field.HashidAutoField(
                        alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
                        editable=False,
                        min_length=3,
                        primary_key=True,
                        serialize=False,
                        verbose_name='Readable postcard ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'face',
                    models.ImageField(
                        blank=True,
                        upload_to='postcards/',
                        verbose_name='Postcard face design',
                    ),
                ),
                (
                    'from_country',
                    django_countries.fields.CountryField(max_length=2),
                ),
                ('from_city', models.CharField(max_length=32)),
            ],
        )
    ]
