# Generated by Django 2.2.3 on 2019-08-11 19:12

import common.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import postcards.models


class Migration(migrations.Migration):

    dependencies = [('postcards', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=64)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=32)),
            ],
            bases=(common.models.UUIDMixin, models.Model),
        ),
        migrations.AddField(
            model_name='card',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='face',
            field=models.ImageField(
                blank=True,
                upload_to=postcards.models.face_upload_path,
                verbose_name='Postcard face design',
            ),
        ),
        migrations.AddField(
            model_name='card',
            name='to',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards',
                to='postcards.Contact',
                verbose_name='Receiver',
            ),
        ),
    ]
