# Generated by Django 2.2.3 on 2019-08-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('postcards', '0002_contact_receive_fields')]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cards',
                to='postcards.Contact',
                verbose_name='Receiver',
            ),
        )
    ]
