# Generated by Django 2.2.7 on 2019-12-01 16:21

from django.db import migrations, models
import jiaoge.storage
import postcards.models


class Migration(migrations.Migration):

    dependencies = [
        ("postcards", "0003_card_claim_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("de", "German"),
                    ("pl", "Polish"),
                ],
                default="en",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="face",
            field=models.ImageField(
                blank=True,
                storage=jiaoge.storage.S3MediaStorage(),
                upload_to=postcards.models.face_upload_path,
                verbose_name="Postcard face design",
            ),
        ),
    ]
